### PR TITLE
Dane's progress

### PR DESCRIPTION
**Pull request by Simian-Spectre**
Help?

### CODE REVIEW

**Comment by staslyakhov** [comment]
Pro tip:
50 6c 65 61 73 65 20 66 6f 72 20 74 68 65 20 6c 6f 76 65 20 6f 66 20 67 6f 64 20 75 73 65 20 53 51 4c 21
(ASCII)

**Comment by Simian-Spectre** [comment]
Thanks for wasting my time. Please for the love of god use letters next time. And why would I need SQL? What's wrong with the way I did it?

**Comment by otakaran** [comment]
Hey @Simian-Spectre, good work so far..

> Help

Is not very descriptive. Tell us exactly what you need help with.

**Comment by Aqcurate** [comment]
## Debugging:

First off, bad variable names make it difficult to read. input1, input2, etc... are not very descriptive. But, I do see your problem. I get an error when withdrawing. You try to write the balance in input2.txt, however, the input2 variable is not stored anymore after you restart the program.

*\* input2.txt is undefined and will not work **

Basically, here is the timeline:
Program Start ---> User Registers: test --> input2 = test --> Write into input into id --> Program restarts

*\* Resetting results in input2 being undefined, so the next session will be: **

Program Start --> User Logins --> Withdraw --> Write into input2.txt --> input2 undefined --> ERROR.

Also note, that you store the login input into variable input4 instead of input2 causing this issue.

Good variable names are very important.

## On the note of Github:

Dane, please be more descriptive with your requests. Make sure the comment you posted on discord is on here as well so everyone can read it.

Stan, "use sql" isn't that helpful of advice. At the very least, link some resources to help him understand why he should use your method and how to use your method.

**Comment by Aqcurate** [comment]
I'm also going to merge pull request anyway. This seems stable enough to push into master, despite the minor bug.

**Comment by staslyakhov** [comment]
I believe I already explained how SQL works and we all discussed why it is better, not to mention that I uploaded a working program that uses it on GitHub. If he needs additional help with SQL he can always pm me.

**Pull request merged**
